version: "3.1"

networks:
  workernet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "20.3.0.1/24"
          gateway: "20.3.0.1"
  default:
    driver: bridge

services:
  api:
    image: node
    restart: always
    networks:
      workernet:
        ipv4_address: 20.3.0.7
    ports:
      - 3252:3252
    volumes:
      - .:/usr/0001/
      - /usr/0001/node_modules
    working_dir: /usr/0001
    command: yarn prod
